name: Build and Push Docker Image for k8s-model-operator
on:
  push:
    branches:
      - release/*
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image tag (use text after last slash)
        id: vars
        run: |
          ref="${{ github.ref_name }}"
          tag="${ref##*/}"
          echo "image_tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Basic check for project build and lint
        id: check
        run: |
          make lint && make build && make test

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.image_tag }}
